import 'package:r_form/model/country_model.dart';

final List<Country> countryList = [
  Country(
    isoCode: "AF",
    phoneCode: "93",
    name: "Afghanistan",
    iso3Code: "AFG",
    img: 'assets/flags/af.png',
  ),
  Country(
    isoCode: "AL",
    phoneCode: "355",
    name: "Albania",
    iso3Code: "ALB",
    img: 'assets/flags/al.png',
  ),
  Country(
    isoCode: "DZ",
    phoneCode: "213",
    name: "Algeria",
    iso3Code: "DZA",
    img: 'assets/flags/dz.png',
  ),
  Country(
    isoCode: "AS",
    phoneCode: "1-684",
    name: "American Samoa",
    iso3Code: "ASM",
    img: 'assets/flags/as.png',
  ),
  Country(
    isoCode: "AD",
    phoneCode: "376",
    name: "Andorra",
    iso3Code: "AND",
    img: 'assets/flags/ad.png',
  ),
  Country(
    isoCode: "AO",
    phoneCode: "244",
    name: "Angola",
    iso3Code: "AGO",
    img: 'assets/flags/ao.png',
  ),
  Country(
    isoCode: "AI",
    phoneCode: "1-264",
    name: "Anguilla",
    iso3Code: "AIA",
    img: 'assets/flags/ai.png',
  ),
  Country(
    isoCode: "AQ",
    phoneCode: "672",
    name: "Antarctica",
    iso3Code: "ATA",
    img: 'assets/flags/aq.png',
  ),
  Country(
    isoCode: "AG",
    phoneCode: "1-268",
    name: "Antigua and Barbuda",
    iso3Code: "ATG",
    img: 'assets/flags/ag.png',
  ),
  Country(
    isoCode: "AR",
    phoneCode: "54",
    name: "Argentina",
    iso3Code: "ARG",
    img: 'assets/flags/ar.png',
  ),
  Country(
    isoCode: "AM",
    phoneCode: "374",
    name: "Armenia",
    iso3Code: "ARM",
    img: 'assets/flags/am.png',
  ),
  Country(
    isoCode: "AW",
    phoneCode: "297",
    name: "Aruba",
    iso3Code: "ABW",
    img: 'assets/flags/an.png',
  ),
  Country(
    isoCode: "AU",
    phoneCode: "61",
    name: "Australia",
    iso3Code: "AUS",
    img: 'assets/flags/au.png',
  ),
  Country(
    isoCode: "AT",
    phoneCode: "43",
    name: "Austria",
    iso3Code: "AUT",
    img: 'assets/flags/at.png',
  ),
  Country(
    isoCode: "AZ",
    phoneCode: "994",
    name: "Azerbaijan",
    iso3Code: "AZE",
    img: 'assets/flags/az.png',
  ),
  Country(
    isoCode: "BS",
    phoneCode: "1-242",
    name: "Bahamas",
    iso3Code: "BHS",
    img: 'assets/flags/bs.png',
  ),
  Country(
    isoCode: "BH",
    phoneCode: "973",
    name: "Bahrain",
    iso3Code: "BHR",
    img: 'assets/flags/bh.png',
  ),
  Country(
    isoCode: "BD",
    phoneCode: "880",
    name: "Bangladesh",
    iso3Code: "BGD",
    img: 'assets/flags/bd.png',
  ),
  Country(
    isoCode: "BD",
    phoneCode: "1-246",
    name: "Barbados",
    iso3Code: "BRB",
    img: 'assets/flags/bd.png',
  ),
  Country(
    isoCode: "BY",
    phoneCode: "375",
    name: "Belarus",
    iso3Code: "BLR",
    img: 'assets/flags/by.png',
  ),
  Country(
    isoCode: "BE",
    phoneCode: "32",
    name: "Belgium",
    iso3Code: "BEL",
    img: 'assets/flags/be.png',
  ),
  Country(
    isoCode: "BZ",
    phoneCode: "501",
    name: "Belize",
    iso3Code: "BLZ",
    img: 'assets/flags/bz.png',
  ),
  Country(
    isoCode: "BJ",
    phoneCode: "229",
    name: "Benin",
    iso3Code: "BEN",
    img: 'assets/flags/bj.png',
  ),
  Country(
    isoCode: "BM",
    phoneCode: "1-441",
    name: "Bermuda",
    iso3Code: "BMU",
    img: 'assets/flags/bm.png',
  ),
  Country(
    isoCode: "BT",
    phoneCode: "975",
    name: "Bhutan",
    iso3Code: "BTN",
    img: 'assets/flags/bt.png',
  ),
  Country(
    isoCode: "BO",
    phoneCode: "591",
    name: "Bolivia, Plurinational State of",
    iso3Code: "BOL",
    img: 'assets/flags/bo.png',
  ),
  Country(
    isoCode: "BA",
    phoneCode: "387",
    name: "Bosnia and Herzegovina",
    iso3Code: "BIH",
    img: 'assets/flags/ba.png',
  ),
  Country(
    isoCode: "BW",
    phoneCode: "267",
    name: "Botswana",
    iso3Code: "BWA",
    img: 'assets/flags/bw.png',
  ),
  Country(
    isoCode: "BV",
    phoneCode: "47",
    name: "Bouvet Island",
    iso3Code: "BVT",
    img: 'assets/flags/bv.png',
  ),
  Country(
    isoCode: "BR",
    phoneCode: "55",
    name: "Brazil",
    iso3Code: "BRA",
    img: 'assets/flags/br.png',
  ),
  Country(
    isoCode: "IO",
    phoneCode: "246",
    name: "British Indian Ocean Territory",
    iso3Code: "IOT",
    img: 'assets/flags/io.png',
  ),
  Country(
    isoCode: "BN",
    phoneCode: "673",
    name: "Brunei Darussalam",
    iso3Code: "BRN",
    img: 'assets/flags/bn.png',
  ),
  Country(
    isoCode: "BG",
    phoneCode: "359",
    name: "Bulgaria",
    iso3Code: "BGR",
    img: 'assets/flags/bg.png',
  ),
  Country(
    isoCode: "BF",
    phoneCode: "226",
    name: "Burkina Faso",
    iso3Code: "BFA",
    img: 'assets/flags/bf.png',
  ),
  Country(
    isoCode: "BI",
    phoneCode: "257",
    name: "Burundi",
    iso3Code: "BDI",
    img: 'assets/flags/bi.png',
  ),
  Country(
    isoCode: "KH",
    phoneCode: "855",
    name: "Cambodia",
    iso3Code: "KHM",
    img: 'assets/flags/kh.png',
  ),
  Country(
    isoCode: "CM",
    phoneCode: "237",
    name: "Cameroon",
    iso3Code: "CMR",
    img: 'assets/flags/cm.png',
  ),
  Country(
    isoCode: "CA",
    phoneCode: "1",
    name: "Canada",
    iso3Code: "CAN",
    img: 'assets/flags/ca.png',
  ),
  Country(
    isoCode: "CV",
    phoneCode: "238",
    name: "Cape Verde",
    iso3Code: "CPV",
    img: 'assets/flags/cv.png',
  ),
  Country(
    isoCode: "BQ",
    phoneCode: "599",
    name: "Caribbean Netherlands",
    iso3Code: "BES",
    img: 'assets/flags/bq.png',
  ),
  Country(
    isoCode: "KY",
    phoneCode: "1-345",
    name: "Cayman Islands",
    iso3Code: "CYM",
    img: 'assets/flags/ky.png',
  ),
  Country(
    isoCode: "CF",
    phoneCode: "236",
    name: "Central African Republic",
    iso3Code: "CAF",
    img: 'assets/flags/cf.png',
  ),
  Country(
    isoCode: "TD",
    phoneCode: "235",
    name: "Chad",
    iso3Code: "TCD",
    img: 'assets/flags/td.png',
  ),
  Country(
    isoCode: "CL",
    phoneCode: "56",
    name: "Chile",
    iso3Code: "CHL",
    img: 'assets/flags/cl.png',
  ),
  Country(
    isoCode: "CN",
    phoneCode: "86",
    name: "China",
    iso3Code: "CHN",
    img: 'assets/flags/cn.png',
  ),
  Country(
    isoCode: "CX",
    phoneCode: "61",
    name: "Christmas Island",
    iso3Code: "CXR",
    img: 'assets/flags/cx.png',
  ),
  Country(
    isoCode: "CC",
    phoneCode: "61",
    name: "Cocos (Keeling) Islands",
    iso3Code: "CCK",
    img: 'assets/flags/cc.png',
  ),
  Country(
    isoCode: "CO",
    phoneCode: "57",
    name: "Colombia",
    iso3Code: "COL",
    img: 'assets/flags/co.png',
  ),
  Country(
    isoCode: "KM",
    phoneCode: "269",
    name: "Comoros",
    iso3Code: "COM",
    img: 'assets/flags/km.png',
  ),
  Country(
    isoCode: "CG",
    phoneCode: "242",
    name: "Congo",
    iso3Code: "COG",
    img: 'assets/flags/cg.png',
  ),
  Country(
    isoCode: "CD",
    phoneCode: "243",
    name: "Congo, the Democratic Republic of the",
    iso3Code: "COD",
    img: 'assets/flags/co.png',
  ),
  Country(
    isoCode: "CK",
    phoneCode: "682",
    name: "Cook Islands",
    iso3Code: "COK",
    img: 'assets/flags/ck.png',
  ),
  Country(
    isoCode: "CR",
    phoneCode: "506",
    name: "Costa Rica",
    iso3Code: "CRI",
    img: 'assets/flags/cr.png',
  ),
  Country(
    isoCode: "HR",
    phoneCode: "385",
    name: "Croatia",
    iso3Code: "HRV",
    img: 'assets/flags/hr.png',
  ),
  Country(
    isoCode: "CU",
    phoneCode: "53",
    name: "Cuba",
    iso3Code: "CUB",
    img: 'assets/flags/cu.png',
  ),
  Country(
    isoCode: "CW",
    phoneCode: "599",
    name: "Curaçao",
    iso3Code: "CUW",
    img: 'assets/flags/cw.png',
  ),
  Country(
    isoCode: "CY",
    phoneCode: "357",
    name: "Cyprus",
    iso3Code: "CYP",
    img: 'assets/flags/cy.png',
  ),
  Country(
    isoCode: "CZ",
    phoneCode: "420",
    name: "Czech Republic",
    iso3Code: "CZE",
    img: 'assets/flags/cz.png',
  ),
  Country(
    isoCode: "CI",
    phoneCode: "225",
    name: "Côte d'Ivoire",
    iso3Code: "CIV",
    img: 'assets/flags/ci.png',
  ),
  Country(
    isoCode: "DK",
    phoneCode: "45",
    name: "Denmark",
    iso3Code: "DNK",
    img: 'assets/flags/dk.png',
  ),
  Country(
    isoCode: "DJ",
    phoneCode: "253",
    name: "Djibouti",
    iso3Code: "DJI",
    img: 'assets/flags/dj.png',
  ),
  Country(
    isoCode: "DM",
    phoneCode: "1-767",
    img: 'assets/flags/dm.png',
    name: "Dominica",
    iso3Code: "DMA",
  ),
  Country(
    isoCode: "DO",
    phoneCode: "1-849",
    name: "Dominican Republic",
    iso3Code: "DOM",
    img: 'assets/flags/do.png',
  ),
  Country(
    isoCode: "EC",
    phoneCode: "593",
    name: "Ecuador",
    img: 'assets/flags/ec.png',
    iso3Code: "ECU",
  ),
  Country(
    isoCode: "EG",
    phoneCode: "20",
    name: "Egypt",
    img: 'assets/flags/eg.png',
    iso3Code: "EGY",
  ),
  Country(
    isoCode: "SV",
    phoneCode: "503",
    name: "El Salvador",
    iso3Code: "SLV",
    img: 'assets/flags/sv.png',
  ),
  // Country(
  //   isoCode: "GB-ENG",
  //   phoneCode: "44",
  //   name: "England",
  //   iso3Code: "GBR",
  //   img: 'assets/flags/by.png',
  // ),
  Country(
    isoCode: "GQ",
    phoneCode: "240",
    name: "Equatorial Guinea",
    iso3Code: "GNQ",
    img: 'assets/flags/gq.png',
  ),
  Country(
    isoCode: "ER",
    phoneCode: "291",
    name: "Eritrea",
    iso3Code: "ERI",
    img: 'assets/flags/er.png',
  ),
  Country(
    isoCode: "EE",
    phoneCode: "372",
    name: "Estonia",
    img: 'assets/flags/ee.png',
    iso3Code: "EST",
  ),
  Country(
    isoCode: "ET",
    phoneCode: "251",
    name: "Ethiopia",
    iso3Code: "ETH",
    img: 'assets/flags/et.png',
  ),
  Country(
    isoCode: "FK",
    phoneCode: "500",
    name: "Falkland Islands (Malvinas)",
    iso3Code: "FLK",
    img: 'assets/flags/fk.png',
  ),
  Country(
    isoCode: "FO",
    phoneCode: "298",
    img: 'assets/flags/fo.png',
    name: "Faroe Islands",
    iso3Code: "FRO",
  ),
  Country(
    isoCode: "FJ",
    phoneCode: "679",
    name: "Fiji",
    iso3Code: "FJI",
    img: 'assets/flags/fj.png',
  ),
  Country(
    isoCode: "FI",
    phoneCode: "358",
    name: "Finland",
    iso3Code: "FIN",
    img: 'assets/flags/fi.png',
  ),
  Country(
    isoCode: "FR",
    phoneCode: "33",
    name: "France",
    img: 'assets/flags/fr.png',
    iso3Code: "FRA",
  ),
  Country(
    isoCode: "GF",
    phoneCode: "594",
    name: "French Guiana",
    img: 'assets/flags/gf.png',
    iso3Code: "GUF",
  ),
  Country(
    isoCode: "PF",
    phoneCode: "689",
    name: "French Polynesia",
    iso3Code: "PYF",
    img: 'assets/flags/pf.png',
  ),
  Country(
    isoCode: "TF",
    phoneCode: "262",
    name: "French Southern Territories",
    iso3Code: "ATF",
    img: 'assets/flags/tf.png',
  ),
  Country(
    isoCode: "GA",
    img: 'assets/flags/ga.png',
    phoneCode: "241",
    name: "Gabon",
    iso3Code: "GAB",
  ),
  Country(
    isoCode: "GM",
    phoneCode: "220",
    name: "Gambia",
    iso3Code: "GMB",
    img: 'assets/flags/gm.png',
  ),
  Country(
    isoCode: "GE",
    phoneCode: "995",
    img: 'assets/flags/ge.png',
    name: "Georgia",
    iso3Code: "GEO",
  ),
  Country(
    isoCode: "DE",
    phoneCode: "49",
    img: 'assets/flags/de.png',
    name: "Germany",
    iso3Code: "DEU",
  ),
  Country(
    isoCode: "GH",
    phoneCode: "233",
    name: "Ghana",
    iso3Code: "GHA",
    img: 'assets/flags/gh.png',
  ),
  Country(
    isoCode: "GI",
    phoneCode: "350",
    name: "Gibraltar",
    img: 'assets/flags/gi.png',
    iso3Code: "GIB",
  ),
  Country(
    isoCode: "GR",
    phoneCode: "30",
    name: "Greece",
    iso3Code: "GRC",
    img: 'assets/flags/gr.png',
  ),
  Country(
    isoCode: "GL",
    phoneCode: "299",
    name: "Greenland",
    iso3Code: "GRL",
    img: 'assets/flags/gl.png',
  ),
  Country(
    isoCode: "GD",
    phoneCode: "1-473",
    img: 'assets/flags/gd.png',
    name: "Grenada",
    iso3Code: "GRD",
  ),
  Country(
    isoCode: "GP",
    phoneCode: "590",
    name: "Guadeloupe",
    iso3Code: "GLP",
    img: 'assets/flags/gp.png',
  ),
  Country(
    isoCode: "GU",
    phoneCode: "1-671",
    name: "Guam",
    img: 'assets/flags/gu.png',
    iso3Code: "GUM",
  ),
  Country(
    isoCode: "GT",
    phoneCode: "502",
    name: "Guatemala",
    img: 'assets/flags/gt.png',
    iso3Code: "GTM",
  ),
  Country(
    isoCode: "GG",
    phoneCode: "44-1481",
    name: "Guernsey",
    img: 'assets/flags/gg.png',
    iso3Code: "GGY",
  ),
  Country(
    isoCode: "GN",
    phoneCode: "224",
    name: "Guinea",
    iso3Code: "GIN",
    img: 'assets/flags/gn.png',
  ),
  Country(
    isoCode: "GW",
    phoneCode: "245",
    name: "Guinea-Bissau",
    img: 'assets/flags/gw.png',
    iso3Code: "GNB",
  ),
  Country(
    isoCode: "GY",
    phoneCode: "592",
    name: "Guyana",
    iso3Code: "GUY",
    img: 'assets/flags/gy.png',
  ),
  Country(
    isoCode: "HT",
    phoneCode: "509",
    name: "Haiti",
    img: 'assets/flags/ht.png',
    iso3Code: "HTI",
  ),
  Country(
    isoCode: "HM",
    phoneCode: "672",
    name: "Heard Island and McDonald Islands",
    img: 'assets/flags/hm.png',
    iso3Code: "HMD",
  ),
  Country(
    isoCode: "VA",
    phoneCode: "379",
    name: "Holy See (Vatican City State)",
    img: 'assets/flags/va.png',
    iso3Code: "VAT",
  ),
  Country(
    isoCode: "HN",
    phoneCode: "504",
    name: "Honduras",
    img: 'assets/flags/hn.png',
    iso3Code: "HND",
  ),
  Country(
    isoCode: "HK",
    phoneCode: "852",
    img: 'assets/flags/hk.png',
    name: "Hong Kong",
    iso3Code: "HKG",
  ),
  Country(
    isoCode: "HU",
    phoneCode: "36",
    img: 'assets/flags/hu.png',
    name: "Hungary",
    iso3Code: "HUN",
  ),
  Country(
    isoCode: "IS",
    phoneCode: "354",
    name: "Iceland",
    img: 'assets/flags/is.png',
    iso3Code: "ISL",
  ),
  Country(
    isoCode: "IN",
    phoneCode: "91",
    img: 'assets/flags/in.png',
    name: "India",
    iso3Code: "IND",
  ),
  Country(
    isoCode: "ID",
    phoneCode: "62",
    name: "Indonesia",
    img: 'assets/flags/id.png',
    iso3Code: "IDN",
  ),
  Country(
    isoCode: "IR",
    phoneCode: "98",
    name: "Iran, Islamic Republic of",
    iso3Code: "IRN",
    img: 'assets/flags/ir.png',
  ),
  Country(
    isoCode: "IQ",
    phoneCode: "964",
    name: "Iraq",
    iso3Code: "IRQ",
    img: 'assets/flags/iq.png',
  ),
  Country(
    isoCode: "IE",
    phoneCode: "353",
    name: "Ireland",
    img: 'assets/flags/ie.png',
    iso3Code: "IRL",
  ),
  Country(
    isoCode: "IM",
    phoneCode: "44-1624",
    name: "Isle of Man",
    img: 'assets/flags/im.png',
    iso3Code: "IMN",
  ),
  Country(
    isoCode: "IL",
    phoneCode: "972",
    img: 'assets/flags/il.png',
    name: "Israel",
    iso3Code: "ISR",
  ),
  Country(
    isoCode: "IT",
    phoneCode: "39",
    name: "Italy",
    img: 'assets/flags/it.png',
    iso3Code: "ITA",
  ),
  Country(
    isoCode: "JM",
    phoneCode: "1-876",
    name: "Jamaica",
    img: 'assets/flags/jm.png',
    iso3Code: "JAM",
  ),
  Country(
    isoCode: "JP",
    phoneCode: "81",
    name: "Japan",
    img: 'assets/flags/jp.png',
    iso3Code: "JPN",
  ),
  Country(
    isoCode: "JE",
    phoneCode: "44-1534",
    name: "Jersey",
    img: 'assets/flags/je.png',
    iso3Code: "JEY",
  ),
  Country(
    isoCode: "JO",
    phoneCode: "962",
    name: "Jordan",
    img: 'assets/flags/jo.png',
    iso3Code: "JOR",
  ),
  Country(
    isoCode: "KZ",
    phoneCode: "7",
    img: 'assets/flags/kz.png',
    name: "Kazakhstan",
    iso3Code: "KAZ",
  ),
  Country(
    isoCode: "KE",
    phoneCode: "254",
    name: "Kenya",
    img: 'assets/flags/ke.png',
    iso3Code: "KEN",
  ),
  Country(
    isoCode: "KI",
    phoneCode: "686",
    name: "Kiribati",
    img: 'assets/flags/ki.png',
    iso3Code: "KIR",
  ),
  Country(
    isoCode: "KP",
    phoneCode: "850",
    name: "Korea, Democratic People's Republic of",
    img: 'assets/flags/kp.png',
    iso3Code: "PRK",
  ),
  Country(
    isoCode: "KR",
    phoneCode: "82",
    name: "Korea, Republic of",
    img: 'assets/flags/kr.png',
    iso3Code: "KOR",
  ),
  Country(
    isoCode: "XK",
    phoneCode: "383",
    name: "Kosovo",
    img: 'assets/flags/bxky.png',
    iso3Code: "KOS",
  ),
  Country(
    isoCode: "KW",
    img: 'assets/flags/kw.png',
    phoneCode: "965",
    name: "Kuwait",
    iso3Code: "KWT",
  ),
  Country(
    isoCode: "KG",
    phoneCode: "996",
    name: "Kyrgyzstan",
    img: 'assets/flags/kg.png',
    iso3Code: "KGZ",
  ),
  Country(
    isoCode: "LA",
    phoneCode: "856",
    name: "Lao People's Democratic Republic",
    img: 'assets/flags/la.png',
    iso3Code: "LAO",
  ),
  Country(
    isoCode: "LV",
    phoneCode: "371",
    name: "Latvia",
    img: 'assets/flags/lv.png',
    iso3Code: "LVA",
  ),
  Country(
    isoCode: "LB",
    phoneCode: "961",
    name: "Lebanon",
    img: 'assets/flags/lb.png',
    iso3Code: "LBN",
  ),
  Country(
    isoCode: "LS",
    phoneCode: "266",
    name: "Lesotho",
    iso3Code: "LSO",
    img: 'assets/flags/ls.png',
  ),
  Country(
    isoCode: "LR",
    phoneCode: "231",
    img: 'assets/flags/lr.png',
    name: "Liberia",
    iso3Code: "LBR",
  ),
  Country(
    isoCode: "LY",
    phoneCode: "218",
    name: "Libya",
    img: 'assets/flags/ly.png',
    iso3Code: "LBY",
  ),
  Country(
    isoCode: "LI",
    phoneCode: "423",
    img: 'assets/flags/lt.png',
    name: "Liechtenstein",
    iso3Code: "LIE",
  ),
  Country(
    isoCode: "LT",
    phoneCode: "370",
    name: "Lithuania",
    img: 'assets/flags/lt.png',
    iso3Code: "LTU",
  ),
  Country(
    isoCode: "LU",
    phoneCode: "352",
    name: "Luxembourg",
    img: 'assets/flags/lu.png',
    iso3Code: "LUX",
  ),
  Country(
    isoCode: "MO",
    phoneCode: "853",
    name: "Macao",
    img: 'assets/flags/mo.png',
    iso3Code: "MAC",
  ),
  Country(
    isoCode: "MK",
    phoneCode: "389",
    img: 'assets/flags/mk.png',
    name: "Macedonia, the former Yugoslav Republic of",
    iso3Code: "MKD",
  ),
  Country(
    isoCode: "MG",
    phoneCode: "261",
    name: "Madagascar",
    img: 'assets/flags/mg.png',
    iso3Code: "MDG",
  ),
  Country(
    isoCode: "MW",
    phoneCode: "265",
    img: 'assets/flags/mw.png',
    name: "Malawi",
    iso3Code: "MWI",
  ),
  Country(
    isoCode: "MY",
    phoneCode: "60",
    name: "Malaysia",
    img: 'assets/flags/my.png',
    iso3Code: "MYS",
  ),
  Country(
    isoCode: "MV",
    phoneCode: "960",
    name: "Maldives",
    img: 'assets/flags/mv.png',
    iso3Code: "MDV",
  ),
  Country(
    isoCode: "ML",
    phoneCode: "223",
    img: 'assets/flags/ml.png',
    name: "Mali",
    iso3Code: "MLI",
  ),
  Country(
    isoCode: "MT",
    phoneCode: "356",
    name: "Malta",
    img: 'assets/flags/mt.png',
    iso3Code: "MLT",
  ),
  Country(
    isoCode: "MH",
    phoneCode: "692",
    img: 'assets/flags/mh.png',
    name: "Marshall Islands",
    iso3Code: "MHL",
  ),
  Country(
    isoCode: "MQ",
    phoneCode: "596",
    name: "Martinique",
    iso3Code: "MTQ",
    img: 'assets/flags/mq.png',
  ),
  Country(
    isoCode: "MR",
    phoneCode: "222",
    img: 'assets/flags/mr.png',
    name: "Mauritania",
    iso3Code: "MRT",
  ),
  Country(
    isoCode: "MU",
    phoneCode: "230",
    name: "Mauritius",
    img: 'assets/flags/mu.png',
    iso3Code: "MUS",
  ),
  Country(
    isoCode: "YT",
    phoneCode: "262",
    img: 'assets/flags/yt.png',
    name: "Mayotte",
    iso3Code: "MYT",
  ),
  Country(
    isoCode: "MX",
    phoneCode: "52",
    img: 'assets/flags/mx.png',
    name: "Mexico",
    iso3Code: "MEX",
  ),
  Country(
    isoCode: "FM",
    phoneCode: "691",
    name: "Micronesia, Federated States of",
    img: 'assets/flags/fm.png',
    iso3Code: "FSM",
  ),
  Country(
    isoCode: "MD",
    phoneCode: "373",
    img: 'assets/flags/md.png',
    name: "Moldova, Republic of",
    iso3Code: "MDA",
  ),
  Country(
    isoCode: "MC",
    phoneCode: "377",
    name: "Monaco",
    iso3Code: "MCO",
    img: 'assets/flags/mc.png',
  ),
  Country(
    isoCode: "MN",
    phoneCode: "976",
    name: "Mongolia",
    iso3Code: "MNG",
    img: 'assets/flags/mn.png',
  ),
  Country(
    isoCode: "ME",
    phoneCode: "382",
    img: 'assets/flags/me.png',
    name: "Montenegro",
    iso3Code: "MNE",
  ),
  Country(
    isoCode: "MS",
    phoneCode: "1-664",
    name: "Montserrat",
    iso3Code: "MSR",
    img: 'assets/flags/ms.png',
  ),
  Country(
    isoCode: "MA",
    phoneCode: "212",
    name: "Morocco",
    img: 'assets/flags/ma.png',
    iso3Code: "MAR",
  ),
  Country(
    isoCode: "MZ",
    phoneCode: "258",
    img: 'assets/flags/mz.png',
    name: "Mozambique",
    iso3Code: "MOZ",
  ),
  Country(
    isoCode: "MM",
    phoneCode: "95",
    name: "Myanmar",
    iso3Code: "MMR",
    img: 'assets/flags/mm.png',
  ),
  Country(
    isoCode: "NA",
    phoneCode: "264",
    img: 'assets/flags/na.png',
    name: "Namibia",
    iso3Code: "NAM",
  ),
  Country(
    isoCode: "NR",
    phoneCode: "674",
    name: "Nauru",
    img: 'assets/flags/nr.png',
    iso3Code: "NRU",
  ),
  Country(
    isoCode: "NP",
    phoneCode: "977",
    name: "Nepal",
    img: 'assets/flags/np.png',
    iso3Code: "NPL",
  ),
  Country(
    isoCode: "NL",
    phoneCode: "31",
    name: "Netherlands",
    img: 'assets/flags/nl.png',
    iso3Code: "NLD",
  ),
  Country(
    isoCode: "AN",
    phoneCode: "599",
    name: "Netherlands Antilles",
    img: 'assets/flags/an.png',
    iso3Code: "AN",
  ),
  Country(
    isoCode: "NC",
    img: 'assets/flags/nc.png',
    phoneCode: "687",
    name: "New Caledonia",
    iso3Code: "NCL",
  ),
  Country(
    isoCode: "NZ",
    phoneCode: "64",
    img: 'assets/flags/nz.png',
    name: "New Zealand",
    iso3Code: "NZL",
  ),
  Country(
    isoCode: "NI",
    phoneCode: "505",
    img: 'assets/flags/ni.png',
    name: "Nicaragua",
    iso3Code: "NIC",
  ),
  Country(
    isoCode: "NE",
    phoneCode: "227",
    img: 'assets/flags/ne.png',
    name: "Niger",
    iso3Code: "NER",
  ),
  Country(
    isoCode: "NG",
    phoneCode: "234",
    name: "Nigeria",
    img: 'assets/flags/ng.png',
    iso3Code: "NGA",
  ),
  Country(
    isoCode: "NU",
    phoneCode: "683",
    name: "Niue",
    img: 'assets/flags/nu.png',
    iso3Code: "NIU",
  ),
  Country(
    isoCode: "NF",
    phoneCode: "672",
    name: "Norfolk Island",
    img: 'assets/flags/nf.png',
    iso3Code: "NFK",
  ),
  // Country(
  //   isoCode: "GB-NIR",
  //   img: 'assets/flags/by.png',
  //   phoneCode: "44",
  //   name: "Northern Ireland",
  //   iso3Code: "GBR",
  // ),
  Country(
    isoCode: "MP",
    phoneCode: "1-670",
    img: 'assets/flags/mp.png',
    name: "Northern Mariana Islands",
    iso3Code: "MNP",
  ),
  Country(
    isoCode: "NO",
    img: 'assets/flags/no.png',
    phoneCode: "47",
    name: "Norway",
    iso3Code: "NOR",
  ),
  Country(
    isoCode: "OM",
    phoneCode: "968",
    name: "Oman",
    img: 'assets/flags/om.png',
    iso3Code: "OMN",
  ),
  // Country(
  //   isoCode: "PK",
  //   phoneCode: "92",
  //   name: "Pakistan",
  //   iso3Code: "PAK",
  // ),
  // Country(
  //   isoCode: "PW",
  //   phoneCode: "680",
  //   name: "Palau",
  //   iso3Code: "PLW",
  // ),
  // Country(
  //   isoCode: "PS",
  //   phoneCode: "970",
  //   name: "Palestine",
  //   iso3Code: "PSE",
  // ),
  // Country(
  //   isoCode: "PA",
  //   phoneCode: "507",
  //   name: "Panama",
  //   iso3Code: "PAN",
  // ),
  // Country(
  //   isoCode: "PG",
  //   phoneCode: "675",
  //   name: "Papua New Guinea",
  //   iso3Code: "PNG",
  // ),
  // Country(
  //   isoCode: "PY",
  //   phoneCode: "595",
  //   name: "Paraguay",
  //   iso3Code: "PRY",
  // ),
  // Country(
  //   isoCode: "PE",
  //   phoneCode: "51",
  //   name: "Peru",
  //   iso3Code: "PER",
  // ),
  // Country(
  //   isoCode: "PH",
  //   phoneCode: "63",
  //   name: "Philippines",
  //   iso3Code: "PHL",
  // ),
  // Country(
  //   isoCode: "PN",
  //   phoneCode: "64",
  //   name: "Pitcairn",
  //   iso3Code: "PCN",
  // ),
  // Country(
  //   isoCode: "PL",
  //   phoneCode: "48",
  //   name: "Poland",
  //   iso3Code: "POL",
  // ),
  // Country(
  //   isoCode: "PT",
  //   phoneCode: "351",
  //   name: "Portugal",
  //   iso3Code: "PRT",
  // ),
  // Country(
  //   isoCode: "PR",
  //   phoneCode: "1-787",
  //   name: "Puerto Rico",
  //   iso3Code: "PRI",
  // ),
  // Country(
  //   isoCode: "QA",
  //   phoneCode: "974",
  //   name: "Qatar",
  //   iso3Code: "QAT",
  // ),
  // Country(
  //   isoCode: "RO",
  //   phoneCode: "40",
  //   name: "Romania",
  //   iso3Code: "ROU",
  // ),
  // Country(
  //   isoCode: "RU",
  //   phoneCode: "7",
  //   name: "Russian Federation",
  //   iso3Code: "RUS",
  // ),
  // Country(
  //   isoCode: "RW",
  //   phoneCode: "250",
  //   name: "Rwanda",
  //   iso3Code: "RWA",
  // ),
  // Country(
  //   isoCode: "RE",
  //   phoneCode: "262",
  //   name: "Réunion",
  //   iso3Code: "REU",
  // ),
  // Country(
  //   isoCode: "BL",
  //   phoneCode: "590",
  //   name: "Saint Barthélemy",
  //   iso3Code: "BLM",
  // ),
  // Country(
  //   isoCode: "SH",
  //   phoneCode: "290",
  //   name: "Saint Helena, Ascension and Tristan da Cunha",
  //   iso3Code: "SHN",
  // ),
  // Country(
  //   isoCode: "KN",
  //   phoneCode: "1-869",
  //   name: "Saint Kitts and Nevis",
  //   iso3Code: "KNA",
  // ),
  // Country(
  //   isoCode: "LC",
  //   phoneCode: "1-758",
  //   name: "Saint Lucia",
  //   iso3Code: "LCA",
  // ),
  // Country(
  //   isoCode: "MF",
  //   phoneCode: "590",
  //   name: "Saint Martin",
  //   iso3Code: "MAF",
  // ),
  // Country(
  //   isoCode: "PM",
  //   phoneCode: "508",
  //   name: "Saint Pierre and Miquelon",
  //   iso3Code: "SPM",
  // ),
  // Country(
  //   isoCode: "VC",
  //   phoneCode: "1-784",
  //   name: "Saint Vincent and the Grenadines",
  //   iso3Code: "VCT",
  // ),
  // Country(
  //   isoCode: "WS",
  //   phoneCode: "685",
  //   name: "Samoa",
  //   iso3Code: "WSM",
  // ),
  // Country(
  //   isoCode: "SM",
  //   phoneCode: "378",
  //   name: "San Marino",
  //   iso3Code: "SMR",
  // ),
  // Country(
  //   isoCode: "ST",
  //   phoneCode: "239",
  //   name: "Sao Tome and Principe",
  //   iso3Code: "STP",
  // ),
  // Country(
  //   isoCode: "SA",
  //   phoneCode: "966",
  //   name: "Saudi Arabia",
  //   iso3Code: "SAU",
  // ),
  // Country(
  //   isoCode: "GB-SCT",
  //   phoneCode: "44",
  //   name: "Scotland",
  //   iso3Code: "GBR",
  // ),
  // Country(
  //   isoCode: "SN",
  //   phoneCode: "221",
  //   name: "Senegal",
  //   iso3Code: "SEN",
  // ),
  // Country(
  //   isoCode: "RS",
  //   phoneCode: "381",
  //   name: "Serbia",
  //   iso3Code: "SRB",
  // ),
  // Country(
  //   isoCode: "SC",
  //   phoneCode: "248",
  //   name: "Seychelles",
  //   iso3Code: "SYC",
  // ),
  // Country(
  //   isoCode: "SL",
  //   phoneCode: "232",
  //   name: "Sierra Leone",
  //   iso3Code: "SLE",
  // ),
  // Country(
  //   isoCode: "SG",
  //   phoneCode: "65",
  //   name: "Singapore",
  //   iso3Code: "SGP",
  // ),
  // Country(
  //   isoCode: "SX",
  //   phoneCode: "1-721",
  //   name: "Sint Maarten (Dutch part)",
  //   iso3Code: "SXM",
  // ),
  // Country(
  //   isoCode: "SK",
  //   phoneCode: "421",
  //   name: "Slovakia",
  //   iso3Code: "SVK",
  // ),
  Country(
    isoCode: "SI",
    phoneCode: "386",
    name: "Slovenia",
    iso3Code: "SVN",
    img: 'assets/flags/si.png',
  ),
  Country(
    isoCode: "SB",
    phoneCode: "677",
    name: "Solomon Islands",
    iso3Code: "SLB",
    img: 'assets/flags/sb.png',
  ),
  Country(
    isoCode: "SO",
    phoneCode: "252",
    name: "Somalia",
    iso3Code: "SOM",
    img: 'assets/flags/so.png',
  ),
  Country(
    isoCode: "ZA",
    phoneCode: "27",
    name: "South Africa",
    iso3Code: "ZAF",
    img: 'assets/flags/za.png',
  ),
  Country(
    isoCode: "GS",
    phoneCode: "500",
    name: "South Georgia and the South Sandwich Islands",
    iso3Code: "SGS",
    img: 'assets/flags/gs.png',
  ),
  Country(
    isoCode: "SS",
    phoneCode: "211",
    name: "South Sudan",
    iso3Code: "SSD",
    img: 'assets/flags/ss.png',
  ),
  Country(
    isoCode: "ES",
    phoneCode: "34",
    name: "Spain",
    iso3Code: "ESP",
    img: 'assets/flags/es.png',
  ),
  Country(
    isoCode: "LK",
    phoneCode: "94",
    name: "Sri Lanka",
    iso3Code: "LKA",
    img: 'assets/flags/lk.png',
  ),
  Country(
    isoCode: "SD",
    phoneCode: "249",
    name: "Sudan",
    iso3Code: "SDN",
    img: 'assets/flags/sd.png',
  ),
  Country(
    isoCode: "SR",
    phoneCode: "597",
    name: "Suriname",
    iso3Code: "SUR",
    img: 'assets/flags/sr.png',
  ),
  Country(
    isoCode: "SJ",
    phoneCode: "47",
    name: "Svalbard and Jan Mayen Islands",
    img: 'assets/flags/sj.png',
    iso3Code: "SJM",
  ),
  Country(
    isoCode: "SZ",
    phoneCode: "268",
    name: "Swaziland",
    iso3Code: "SWZ",
    img: 'assets/flags/sz.png',
  ),
  Country(
    isoCode: "SE",
    phoneCode: "46",
    name: "Sweden",
    iso3Code: "SWE",
    img: 'assets/flags/se.png',
  ),
  Country(
    isoCode: "CH",
    phoneCode: "41",
    name: "Switzerland",
    iso3Code: "CHE",
    img: 'assets/flags/ch.png',
  ),
  Country(
    isoCode: "SY",
    phoneCode: "963",
    name: "Syrian Arab Republic",
    img: 'assets/flags/sy.png',
    iso3Code: "SYR",
  ),
  Country(
    isoCode: "TW",
    phoneCode: "886",
    img: 'assets/flags/tw.png',
    name: "Taiwan",
    iso3Code: "TWN",
  ),
  Country(
    isoCode: "TJ",
    phoneCode: "992",
    name: "Tajikistan",
    img: 'assets/flags/tj.png',
    iso3Code: "TJK",
  ),
  Country(
    isoCode: "TZ",
    phoneCode: "255",
    img: 'assets/flags/tz.png',
    name: "Tanzania, United Republic of",
    iso3Code: "TZA",
  ),
  Country(
    isoCode: "TH",
    phoneCode: "66",
    name: "Thailand",
    iso3Code: "THA",
    img: 'assets/flags/th.png',
  ),
  Country(
    isoCode: "TL",
    phoneCode: "670",
    name: "Timor-Leste",
    iso3Code: "TLS",
    img: 'assets/flags/tl.png',
  ),
  Country(
    isoCode: "TG",
    phoneCode: "228",
    name: "Togo",
    iso3Code: "TGO",
    img: 'assets/flags/tg.png',
  ),
  Country(
    isoCode: "TK",
    phoneCode: "690",
    img: 'assets/flags/tk.png',
    name: "Tokelau",
    iso3Code: "TKL",
  ),
  Country(
    isoCode: "TO",
    phoneCode: "676",
    img: 'assets/flags/to.png',
    name: "Tonga",
    iso3Code: "TON",
  ),
  Country(
    isoCode: "TT",
    phoneCode: "1-868",
    name: "Trinidad and Tobago",
    img: 'assets/flags/tt.png',
    iso3Code: "TTO",
  ),
  Country(
    isoCode: "TN",
    phoneCode: "216",
    name: "Tunisia",
    iso3Code: "TUN",
    img: 'assets/flags/tn.png',
  ),
  Country(
    isoCode: "TR",
    phoneCode: "90",
    name: "Turkey",
    iso3Code: "TUR",
    img: 'assets/flags/tr.png',
  ),
  Country(
    isoCode: "TM",
    phoneCode: "993",
    name: "Turkmenistan",
    img: 'assets/flags/tm.png',
    iso3Code: "TKM",
  ),
  Country(
    isoCode: "TC",
    phoneCode: "1-649",
    name: "Turks and Caicos Islands",
    iso3Code: "TCA",
    img: 'assets/flags/tc.png',
  ),
  Country(
    isoCode: "TV",
    phoneCode: "688",
    name: "Tuvalu",
    iso3Code: "TUV",
    img: 'assets/flags/tv.png',
  ),
  Country(
    isoCode: "UG",
    phoneCode: "256",
    name: "Uganda",
    iso3Code: "UGA",
    img: 'assets/flags/ug.png',
  ),
  Country(
    isoCode: "UA",
    phoneCode: "380",
    name: "Ukraine",
    iso3Code: "UKR",
    img: 'assets/flags/ua.png',
  ),
  Country(
    isoCode: "AE",
    phoneCode: "971",
    name: "United Arab Emirates",
    iso3Code: "ARE",
    img: 'assets/flags/ae.png',
  ),
  Country(
    isoCode: "GB",
    phoneCode: "44",
    name: "United Kingdom",
    img: 'assets/flags/gb.png',
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "US",
    phoneCode: "1",
    name: "United States",
    iso3Code: "USA",
    img: 'assets/flags/us.png',
  ),
  Country(
    isoCode: "UY",
    phoneCode: "598",
    name: "Uruguay",
    iso3Code: "URY",
    img: 'assets/flags/uy.png',
  ),
  Country(
    isoCode: "UM",
    phoneCode: "1",
    name: "US Minor Outlying Islands",
    iso3Code: "UMI",
    img: 'assets/flags/um.png',
  ),
  Country(
    isoCode: "UZ",
    phoneCode: "998",
    name: "Uzbekistan",
    iso3Code: "UZB",
    img: 'assets/flags/uz.png',
  ),
  Country(
    isoCode: "VU",
    phoneCode: "678",
    name: "Vanuatu",
    iso3Code: "VUT",
    img: 'assets/flags/vu.png',
  ),
  Country(
    isoCode: "VE",
    phoneCode: "58",
    name: "Venezuela, Bolivarian Republic of",
    iso3Code: "VEN",
    img: 'assets/flags/ve.png',
  ),
  Country(
    isoCode: "VN",
    phoneCode: "84",
    name: "Vietnam",
    img: 'assets/flags/vn.png',
    iso3Code: "VNM",
  ),
  Country(
    isoCode: "VG",
    phoneCode: "1-284",
    name: "Virgin Islands, British",
    iso3Code: "VGB",
    img: 'assets/flags/vg.png',
  ),
  Country(
    isoCode: "VI",
    phoneCode: "1-340",
    name: "Virgin Islands, U.S.",
    iso3Code: "VIR",
    img: 'assets/flags/vi.png',
  ),
  // Country(
  //   isoCode: "GB-WLS",
  //   phoneCode: "44",
  //   name: "Wales",
  //   iso3Code: "GBR",
  //   img: 'assets/flags/by.png',
  // ),
  Country(
    isoCode: "WF",
    phoneCode: "681",
    name: "Wallis and Futuna Islands",
    iso3Code: "WLF",
    img: 'assets/flags/wf.png',
  ),
  Country(
    isoCode: "EH",
    phoneCode: "212",
    name: "Western Sahara",
    iso3Code: "ESH",
    img: 'assets/flags/eh.png',
  ),
  Country(
    isoCode: "YE",
    phoneCode: "967",
    name: "Yemen",
    iso3Code: "YEM",
    img: 'assets/flags/ye.png',
  ),
  Country(
    isoCode: "ZM",
    phoneCode: "260",
    name: "Zambia",
    iso3Code: "ZMB",
    img: 'assets/flags/zm.png',
  ),
  Country(
    isoCode: "ZW",
    phoneCode: "263",
    name: "Zimbabwe",
    iso3Code: "ZWE",
    img: 'assets/flags/zw.png',
  ),
  Country(
    isoCode: "AX",
    phoneCode: "358",
    name: "Åland Islands",
    iso3Code: "ALA",
    img: 'assets/flags/ax.png',
  ),
];
